In [3]:
import pandas as pd

In [ ]:
df=pd.read_csv(r"C:\Users\WorldCupMatches.csv")

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    float64
 1   Datetime              852 non-null    str
 2   Stage                 852 non-null    str
 3   Stadium               852 non-null    str
 4   City                  852 non-null    str
 5   Home Team Name        852 non-null    str
 6   Home Team Goals       852 non-null    float64
 7   Away Team Goals       852 non-null    float64
 8   Away Team Name        852 non-null    str
 9   Win conditions        852 non-null    str
 10  Attendance            850 non-null    float64
 11  Half-time Home Goals  852 non-null    float64
 12  Half-time Away Goals  852 non-null    float64
 13  Referee               852 non-null    str
 14  Assistant 1           852 non-null    str
 15  Assistant 2           852 non-null    str
 16  RoundID               852 non-null    float64
 17  MatchID               852 non-null    float64
 18  Home Team Initials    852 non-null    str
 19  Away Team Initials    852 non-null    str
dtypes: float64(8), str(12)
memory usage: 714.5 KB

In [6]:
df['Datetime']=pd.to_datetime(df['Datetime'],format='mixed')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    float64
 1   Datetime              852 non-null    datetime64[us]
 2   Stage                 852 non-null    str
 3   Stadium               852 non-null    str
 4   City                  852 non-null    str
 5   Home Team Name        852 non-null    str
 6   Home Team Goals       852 non-null    float64
 7   Away Team Goals       852 non-null    float64
 8   Away Team Name        852 non-null    str
 9   Win conditions        852 non-null    str
 10  Attendance            850 non-null    float64
 11  Half-time Home Goals  852 non-null    float64
 12  Half-time Away Goals  852 non-null    float64
 13  Referee               852 non-null    str
 14  Assistant 1           852 non-null    str
 15  Assistant 2           852 non-null    str
 16  RoundID               852 non-null    float64
 17  MatchID               852 non-null    float64
 18  Home Team Initials    852 non-null    str
 19  Away Team Initials    852 non-null    str
dtypes: datetime64[us](1), float64(8), str(11)
memory usage: 714.5 KB

In [8]:
df['Home Team Goals']=pd.to_numeric(df['Home Team Goals'])
df['Home Team Goals']=df['Home Team Goals'].astype('Int64')

In [9]:
df['Home Team Goals'].dtype

Int64Dtype()

In [10]:
df['Home Team Goals']

0          4
1          3
2          2
3          3
4          1
        ...
4567    <NA>
4568    <NA>
4569    <NA>
4570    <NA>
4571    <NA>
Name: Home Team Goals, Length: 4572, dtype: Int64

In [11]:
df['Away Team Goals']=pd.to_numeric(df['Away Team Goals'],errors='coerce')
df['Away Team Goals']=df['Away Team Goals'].astype("Int64")

In [12]:
df['Away Team Goals']

0          1
1          0
2          1
3          1
4          0
        ...
4567    <NA>
4568    <NA>
4569    <NA>
4570    <NA>
4571    <NA>
Name: Away Team Goals, Length: 4572, dtype: Int64

In [13]:
df['Win conditions']=pd.to_numeric(df['Win conditions'],errors='coerce')
df['Win conditions']=df['Win conditions'].astype("Int64")

In [14]:
df = df.drop('Win conditions', axis=1)

In [15]:
df['Attendance']=pd.to_numeric(df['Attendance'],errors="coerce")
df['Attendance']=df['Attendance'].astype('Int64')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    float64
 1   Datetime              852 non-null    datetime64[us]
 2   Stage                 852 non-null    str
 3   Stadium               852 non-null    str
 4   City                  852 non-null    str
 5   Home Team Name        852 non-null    str
 6   Home Team Goals       852 non-null    Int64
 7   Away Team Goals       852 non-null    Int64
 8   Away Team Name        852 non-null    str
 9   Attendance            850 non-null    Int64
 10  Half-time Home Goals  852 non-null    float64
 11  Half-time Away Goals  852 non-null    float64
 12  Referee               852 non-null    str
 13  Assistant 1           852 non-null    str
 14  Assistant 2           852 non-null    str
 15  RoundID               852 non-null    float64
 16  MatchID               852 non-null    float64
 17  Home Team Initials    852 non-null    str
 18  Away Team Initials    852 non-null    str
dtypes: Int64(3), datetime64[us](1), float64(5), str(10)
memory usage: 692.2 KB

In [17]:
df['RoundID']=pd.to_numeric(df['RoundID'],errors='coerce')
df['RoundID']=df['RoundID'].astype('Int64')

In [18]:
df['MatchID']=pd.to_numeric(df['MatchID'],errors="coerce")
df["MatchID"]=df['MatchID'].astype("Int64")

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    float64
 1   Datetime              852 non-null    datetime64[us]
 2   Stage                 852 non-null    str
 3   Stadium               852 non-null    str
 4   City                  852 non-null    str
 5   Home Team Name        852 non-null    str
 6   Home Team Goals       852 non-null    Int64
 7   Away Team Goals       852 non-null    Int64
 8   Away Team Name        852 non-null    str
 9   Attendance            850 non-null    Int64
 10  Half-time Home Goals  852 non-null    float64
 11  Half-time Away Goals  852 non-null    float64
 12  Referee               852 non-null    str
 13  Assistant 1           852 non-null    str
 14  Assistant 2           852 non-null    str
 15  RoundID               852 non-null    Int64
 16  MatchID               852 non-null    Int64
 17  Home Team Initials    852 non-null    str
 18  Away Team Initials    852 non-null    str
dtypes: Int64(5), datetime64[us](1), float64(3), str(10)
memory usage: 701.1 KB

In [20]:
df['Home Team Initials']

0       FRA
1       USA
2       YUG
3       ROU
4       ARG
       ...
4567    NaN
4568    NaN
4569    NaN
4570    NaN
4571    NaN
Name: Home Team Initials, Length: 4572, dtype: str

In [21]:
df['Away Team Initials']

0       MEX
1       BEL
2       BRA
3       PER
4       FRA
       ...
4567    NaN
4568    NaN
4569    NaN
4570    NaN
4571    NaN
Name: Away Team Initials, Length: 4572, dtype: str

In [22]:
df.head(855)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,4444,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930.0,1930-07-13 15:00:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,18346,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930.0,1930-07-14 12:45:00,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,24059,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930.0,1930-07-14 14:50:00,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,2549,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930.0,1930-07-15 16:00:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,23409,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,2014.0,2014-07-12 17:00:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,68034,0.0,2.0,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,300186502,BRA,NED
851,2014.0,2014-07-13 16:00:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,74738,0.0,0.0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,300186501,GER,ARG
852,NaN,NaT,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN
853,NaN,NaT,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN
854,NaN,NaT,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN

In [23]:
df = df.dropna(how='all')

In [24]:
df['Referee']=df['Referee'].str.replace('�','')

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    float64
 1   Datetime              852 non-null    datetime64[us]
 2   Stage                 852 non-null    str
 3   Stadium               852 non-null    str
 4   City                  852 non-null    str
 5   Home Team Name        852 non-null    str
 6   Home Team Goals       852 non-null    Int64
 7   Away Team Goals       852 non-null    Int64
 8   Away Team Name        852 non-null    str
 9   Attendance            850 non-null    Int64
 10  Half-time Home Goals  852 non-null    float64
 11  Half-time Away Goals  852 non-null    float64
 12  Referee               852 non-null    str
 13  Assistant 1           852 non-null    str
 14  Assistant 2           852 non-null    str
 15  RoundID               852 non-null    Int64
 16  MatchID               852 non-null    Int64
 17  Home Team Initials    852 non-null    str
 18  Away Team Initials    852 non-null    str
dtypes: Int64(5), datetime64[us](1), float64(3), str(10)
memory usage: 130.8 KB

In [27]:
print(df['MatchID'].min())   
print(df['MatchID'].max())    
print(df['MatchID'].nunique())

25
300186515
836

In [28]:
df['MatchID'] = range(10001, 10001 + len(df))

In [29]:
df.iloc[100:851]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
100,1954.0,1954-07-04 17:00:00,Final,Wankdorf Stadium,Berne,Germany FR,3,2,Hungary,62500,2.0,2.0,LING William (ENG),ORLANDINI Vincenzo (ITA),GRIFFITHS Benjamin (WAL),3484,10101,FRG,HUN
101,1958.0,1958-06-08 14:00:00,Group 3,Rasunda Stadium,Solna,Sweden,3,0,Mexico,34107,1.0,0.0,LATYCHEV Nikolaj (URS),MOWAT Jack (SCO),ERIKSSON Arne (FIN),220,10102,SWE,MEX
102,1958.0,1958-06-08 19:00:00,Group 4,Nya Ullevi,Gothenburg,Soviet Union,2,2,England,49348,1.0,0.0,ZSOLT Istvan (HUN),NILSEN Birger (NOR),JORGENSEN Carl Frederik (DEN),220,10103,URS,ENG
103,1958.0,1958-06-08 19:00:00,Group 1,Malmo Stadion,Malm�,Argentina,1,3,Germany FR,31156,1.0,2.0,LEAFE Reginald (ENG),HELGE Leo (DEN),AHLNER Sten (SWE),220,10104,ARG,FRG
104,1958.0,1958-06-08 19:00:00,Group 3,Jarnvallen,Sandviken,Hungary,1,1,Wales,15343,1.0,1.0,CODESAL Jose Maria (URU),LEMESIC Leo (YUG),VAN NUFFEL Lucien (BEL),220,10105,HUN,WAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846,2014.0,2014-07-05 13:00:00,Quarter-finals,Estadio Nacional,Brasilia,Argentina,1,0,Belgium,68551,1.0,0.0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255953,10847,ARG,BEL
847,2014.0,2014-07-05 17:00:00,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0,0,Costa Rica,51179,0.0,0.0,Ravshan IRMATOV (UZB),RASULOV Abduxamidullo (UZB),KOCHKAROV Bakhadyr (KGZ),255953,10848,NED,CRC
848,2014.0,2014-07-08 17:00:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1,7,Germany,58141,0.0,5.0,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955,10849,BRA,GER
849,2014.0,2014-07-09 17:00:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,63267,0.0,0.0,Cneyt AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955,10850,NED,ARG
850,2014.0,2014-07-12 17:00:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,68034,0.0,2.0,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,10851,BRA,NED

In [30]:
df['RoundID'] = range(1, len(df) + 1)

In [31]:
df.iloc[100:851]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
100,1954.0,1954-07-04 17:00:00,Final,Wankdorf Stadium,Berne,Germany FR,3,2,Hungary,62500,2.0,2.0,LING William (ENG),ORLANDINI Vincenzo (ITA),GRIFFITHS Benjamin (WAL),101,10101,FRG,HUN
101,1958.0,1958-06-08 14:00:00,Group 3,Rasunda Stadium,Solna,Sweden,3,0,Mexico,34107,1.0,0.0,LATYCHEV Nikolaj (URS),MOWAT Jack (SCO),ERIKSSON Arne (FIN),102,10102,SWE,MEX
102,1958.0,1958-06-08 19:00:00,Group 4,Nya Ullevi,Gothenburg,Soviet Union,2,2,England,49348,1.0,0.0,ZSOLT Istvan (HUN),NILSEN Birger (NOR),JORGENSEN Carl Frederik (DEN),103,10103,URS,ENG
103,1958.0,1958-06-08 19:00:00,Group 1,Malmo Stadion,Malm�,Argentina,1,3,Germany FR,31156,1.0,2.0,LEAFE Reginald (ENG),HELGE Leo (DEN),AHLNER Sten (SWE),104,10104,ARG,FRG
104,1958.0,1958-06-08 19:00:00,Group 3,Jarnvallen,Sandviken,Hungary,1,1,Wales,15343,1.0,1.0,CODESAL Jose Maria (URU),LEMESIC Leo (YUG),VAN NUFFEL Lucien (BEL),105,10105,HUN,WAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846,2014.0,2014-07-05 13:00:00,Quarter-finals,Estadio Nacional,Brasilia,Argentina,1,0,Belgium,68551,1.0,0.0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),847,10847,ARG,BEL
847,2014.0,2014-07-05 17:00:00,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0,0,Costa Rica,51179,0.0,0.0,Ravshan IRMATOV (UZB),RASULOV Abduxamidullo (UZB),KOCHKAROV Bakhadyr (KGZ),848,10848,NED,CRC
848,2014.0,2014-07-08 17:00:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1,7,Germany,58141,0.0,5.0,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),849,10849,BRA,GER
849,2014.0,2014-07-09 17:00:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,63267,0.0,0.0,Cneyt AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),850,10850,NED,ARG
850,2014.0,2014-07-12 17:00:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,68034,0.0,2.0,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),851,10851,BRA,NED

In [34]:
df.to_csv("match_result.csv")